source "https://rubygems.org"
git_source(:github){|repo| "https://github.com/#{repo}.git"}

ruby "2.6.5"

gem "active_model_serializers"
gem "activerecord-import"
gem "bootsnap", ">= 1.4.2", require: false
gem "cancancan"
gem "carrierwave"
gem "config"
gem "devise"
gem "faker"
gem "figaro"
gem "jwt"
gem "kaminari"
gem "mysql2", ">= 0.4.4"
gem "paranoia", "~> 2.2"
gem "puma", "~> 4.1"
gem "rails", "~> 6.0.3", ">= 6.0.3.2"
gem "ransack"
gem "shoulda-matchers"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "database_cleaner"
  gem "factory_bot_rails", require: false
  gem "pry"
  gem "rspec-rails", "~> 4.0.0"
end

group :development do
  gem "listen", "~> 3.2"
  gem "rubocop", "~> 0.74.0", require: false
  gem "rubocop-checkstyle_formatter", require: false
  gem "rubocop-rails", "~> 2.3.2", require: false
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
